services:
  - type: web
    name: customer-identity-reconciliation
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: customer-identity-reconciliation
          property: port
    healthCheckPath: /health